controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\WalletSearch;
use app\models\Wallet;
use app\models\WalletTransactionsSearch;
use app\models\WalletTransactions;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user = Yii::$app->user->identity;
        if($user){
        $searchModel = new WalletSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        // $app->user->identity
        
        $dataProvider->query->andWhere(['user'=>$user->id]);

        $searchModelTransactions = new WalletTransactionsSearch();
        $dataProviderTransactions = $searchModelTransactions->search($this->request->queryParams);
        // $app->user->identity
        
        // $user = Yii::$app->user->identity;
        // $wallet=Wallet::find()->where(['user'=>$user->id])->one()->id;

        $user_id = Wallet::find()->where(['user'=>$user->id])->one()->id;
        // $wallet= WalletTransactions::find()->where(['_from'=>$user->id])->one()->_to;
        

        $dataProviderTransactions->query->andWhere("_from = $user_id OR _to =$user->id");
        

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'searchModelTransactions'=>$searchModelTransactions,
            'dataProviderTransactions'=>$dataProviderTransactions,

        ]);


    }
     else{
        return $this->render('index');
     }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        // $this->layout = 'login';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Users;
use app\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Users models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {

                if( $model->save()){

                    Yii::$app->db->createCommand("INSERT INTO wallet(user,balance) VALUES($model->id,1000)")->execute();
                    return $this->redirect(['..\site\login', 'id' => $model->id]);
                }
                
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/WalletController.php
<?php

namespace app\controllers;

use app\models\Wallet;
use app\models\WalletSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;

/**
 * WalletController implements the CRUD actions for Wallet model.
 */
class WalletController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Wallet models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new WalletSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Wallet model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Wallet model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Wallet();
        $user = Yii::$app->user->identity;
        $wallet=Wallet::find()->where(['user'=>$user->id])->one()->id;
        $bal=Wallet::find()->where(['id'=>$wallet])->one()->balance;
         $model = $this->findModel($wallet);

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                Yii::$app->db->createCommand("UPDATE wallet set balance=$bal+$model->balance where user=$user->id")->execute();
                return $this->redirect(['site/index']);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Wallet model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionRecharge()
    {
        // $model = $this->findModel($id);

      $model=new Wallet(); 
      $user = Yii::$app->user->identity;
      $wallet=Wallet::find()->where(['user'=>$user->id])->one()->id;

       $model = $this->findModel($wallet);
      
       if ($this->request->isPost) {
        if ($model->load($this->request->post())) {

            $model->user=$user->id;

            if($model->save()){
                return $this->redirect(['site/index']);
            }
            
        }
    } else {
        $model->loadDefaultValues();
    }

    return $this->render('recharge', [
        'model' => $model,
    ]);
}

    /**
     * Deletes an existing Wallet model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Wallet model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Wallet the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Wallet::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/WalletTransactionsController.php
<?php

namespace app\controllers;

use app\models\WalletTransactions;
use app\models\WalletTransactionsSearch;
use app\models\Wallet;
use app\models\Users;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;
/**
 * WalletTransactionsController implements the CRUD actions for WalletTransactions model.
 */
class WalletTransactionsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all WalletTransactions models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new WalletTransactionsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single WalletTransactions model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new WalletTransactions model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new WalletTransactions();
        $user = Yii::$app->user->identity;


        $model->_from=Wallet::find()->where(['user'=>$user->id])->one()->id;

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                if($model->amount < 10000){
                    $model->transaction_fee =0;
                }
                else if($model->amount >= 10000 && $model->amount  < 100000 ){
                    $model->transaction_fee =200;
                }
                else{
                    $model->transaction_fee=300;
                }
                 
                // $to= Wallet::find()->where(['id'=>$model->_to])->one()->user;
                $to= Users::find()->where(['id'=>$model->_to])->one()->id;
                $receiver = Users::find()->where(['id'=>$model->_to])->one()->username;

                $receiver_wallet= Wallet::find()->where(['user'=>$to])->one()->id;

                $model->message="Money was sent from ".$user->username. " to ".$receiver;

                if($model->save()){

                    Yii::$app->db->createCommand("UPDATE wallet SET balance = balance - $model->amount - $model->transaction_fee where id = $model->_from")->execute();
                    Yii::$app->db->createCommand("UPDATE wallet SET balance = balance + $model->amount where id = $receiver_wallet")->execute();
                    return $this->redirect(['site/index']);
                }
                

            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing WalletTransactions model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing WalletTransactions model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the WalletTransactions model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return WalletTransactions the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = WalletTransactions::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use app\models\Wallet;
use app\models\Users;

// $user = Yii::$app->user->identity;
// $wallet=Wallet::find()->where(['user'=>$user->id])->one()->id;

// var_dump($wallet);

$this->title = 'E-wallet System';

?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">XYZ E_Wallet</h1><br>
        <p>Welcome to Electronic Wallet</p>
    </div>

<?php if(Yii::$app->user->identity){ ?>
    
    <?php
         $user = Yii::$app->user->identity;
         $wallet=Wallet::find()->where(['user'=>$user->id])->one()->id;
         
    ?>
    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
            <p>
                <?= Html::a(Yii::t('app', 'Recharge!'), ['wallet/create'], ['class' => 'btn btn-primary']) ?>
            </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label'=>'Your account balance',
                'attribute'=>'balance',
            ],
            // [
            //     'class' => ActionColumn::className(),
            //     'urlCreator' => function ($action, app\models\Wallet $model, $key, $index, $column) {
            //         return Url::toRoute([$action, 'id' => $model->id]);
            //      }
            // ],
            // 'balance',
          
        ],
    ]); ?>
     </div>
 
            
    
    <div class="col-lg-8 bg-light">
            <p>
                <?= Html::a(Yii::t('app', 'Send money!'), ['wallet-transactions/create'], ['class' => 'btn btn-primary']) ?>
            </p>
    <h5>Transactions made on your account!</h5><br>
    <?= GridView::widget([
        'dataProvider' => $dataProviderTransactions,
        'filterModel' => $searchModelTransactions,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            // '_to',
            [
                'label'=>'sent from',
                'attribute'=>'_from',
                'value'=>function($model){
                    // $user = Yii::$app->user->identity;
                    
                  $user_id = Wallet::find()->where(['id'=>$model['_from']])->one()->user;
                  return $user = Users::find()->where(['id'=>$user_id])->one()->username;

                }
            ],
            [
                'label'=>'sent to',
                'attribute'=>'_to',
                'value'=>function($model){
                    // $user = Yii::$app->user->identity;
                    
                    // $user_id = Wallet::find()->where(['id'=>$model['_to']])->one()->user;
                  return $user = Users::find()->where(['id'=>$model['_to']])->one()->username;

                }
            ],
            'amount',
            'transaction_fee',
            'message:ntext',
           
            //'_from',
            // [
            //     'class' => ActionColumn::className(),
            //     'urlCreator' => function ($action, app\models\WalletTransactions $model, $key, $index, $column) {
            //         return Url::toRoute([$action, 'id' => $model->id]);
            //      }
            // ],
        ],
    ]); ?>


    </div>
    <?php } else{?>




    </div>
            <div class="col-lg-12 text-center">
               <p>
                Login Here!<br><br> <?= Html::a(Yii::t('app', 'Sign In'), ['site/login'], ['class' => 'btn btn-primary']) ?>
            </p>
            </div>
    <?php } ?>
  
            
            
       

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Login';
?>

<div id="login">

    <h2>
        <span class="fontawesome-lock"></span>Sign In</h2>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',

    /*'fieldConfig' => [
    'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ],*/
    ]); ?>

    <fieldset>
        <p><?= $form->field($model, 'username')->textInput(['autofocus' => true, 'id'=>'username', 'placeholder'=>'username'])->label(false) ?></p>

        <p><?= $form->field($model, 'password')->passwordInput(['id'=>'password', 'placeholder'=>'Your Password'])->label(false) ?> </p>

        <?= Html::submitButton('Sign In', ['class' => 'btn btn-primary pull-right', 'name' => 'login-button']) ?>
    </fieldset>
    
    <p>
       You don't have an account? <?= Html::a(Yii::t('app', 'Sign Up'), ['users/create'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?php ActiveForm::end(); ?>

</div> <!-- end login --> 